[project]
name = "ecobici-rebalanceo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "fastapi>=0.141.1",
    "geopandas>=1.2.0",
    "highspy>=1.15.1",
    "holidays>=0.105",
    "joblib",
    "kneed>=0.8.6",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "numpy",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "scipy",
    "shapely",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
